Repository travelynk/final-project-backend, pull requests merged in 2024-12, with the labels that each got.

#18 Feat Flight Update #1
  .env.example
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  README.md
  prisma/schema.prisma
  src/controllers/__test__/airline.controller.test.js
  src/controllers/__test__/airport.controller.test.js
  src/controllers/__test__/city.controller.test.js
  src/controllers/__test__/country.controller.test.js
  src/controllers/__test__/flight.controller.test.js
  src/controllers/__test__/terminal.controller.test.js
  src/controllers/airline.controller.js
  src/controllers/airport.controller.js
  src/controllers/city.controller.js
  src/controllers/country.controller.js
  src/controllers/flight.controller.js
  src/controllers/index.js
  src/controllers/profile.controller.js
  src/controllers/seat.controllers.js
  src/controllers/terminal.controller.js
  src/middlewares/multer.js
  src/routes/api/v1/airline.route.js
  src/routes/api/v1/airport.route.js
  src/routes/api/v1/city.route.js
  src/routes/api/v1/country.route.js
  src/routes/api/v1/flight.route.js
  src/routes/api/v1/terminal.route.js
  src/services/__test__/airline.service.test.js
  src/services/__test__/airport.service.test.js
  src/services/__test__/auth.service.test.js
  src/services/__test__/city.service.test.js
  src/services/__test__/country.service.test.js
  src/services/__test__/flight.service.test.js
  src/services/__test__/terminal.service.test.js
  src/services/airline.service.js
  src/services/flight.service.js
  src/utils/imagekit.js
Labels: enhancement

#19 New Feat #2
  .env.example
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  README.md
  package.json
  prisma/schema.prisma
  src/controllers/__test__/airline.controller.test.js
  src/controllers/__test__/airport.controller.test.js
  src/controllers/__test__/auth.controller.test.js
  src/controllers/__test__/city.controller.test.js
  src/controllers/__test__/country.controller.test.js
  src/controllers/__test__/flight.controller.test.js
  src/controllers/__test__/terminal.controller.test.js
  src/controllers/airline.controller.js
  src/controllers/airport.controller.js
  src/controllers/auth.controller.js
  src/controllers/city.controller.js
  src/controllers/country.controller.js
  src/controllers/flight.controller.js
  src/controllers/index.js
  src/controllers/profile.controller.js
  src/controllers/seat.controllers.js
  src/controllers/terminal.controller.js
  src/middlewares/errorHandler.js
  src/middlewares/multer.js
  src/routes/api/v1/airline.route.js
  src/routes/api/v1/airport.route.js
  src/routes/api/v1/city.route.js
  src/routes/api/v1/country.route.js
  src/routes/api/v1/flight.route.js
  src/routes/api/v1/index.js
  src/routes/api/v1/terminal.route.js
  src/services/__test__/airline.service.test.js
  src/services/__test__/airport.service.test.js
  src/services/__test__/auth.service.test.js
  src/services/__test__/city.service.test.js
  src/services/__test__/country.service.test.js
  src/services/__test__/flight.service.test.js
  src/services/__test__/terminal.service.test.js
  src/services/airline.service.js
  src/services/airport.service.js
  src/services/auth.service.js
  src/services/city.service.js
  src/services/country.service.js
  src/services/flight.service.js
  src/services/terminal.service.js
  src/utils/generateSeatCode.js
  src/utils/imagekit.js
  src/utils/response.js
  src/validations/airline.validation.js
  src/validations/airport.validation.js
  src/validations/auth.validation.js
  src/validations/city.validation.js
  src/validations/country.validation.js
  src/validations/flight.validation.js
  src/validations/terminal.validation.js
Labels: enhancement

#20 add: auth middleware
  src/controllers/auth.controller.js
  src/middlewares/__test__/auth.test.js
  src/middlewares/auth.js
Labels: enhancement

#21 Update API #3
  README.md
  prisma/schema.prisma
  src/controllers/__test__/auth.controller.test.js
  src/controllers/__test__/country.controller.test.js
  src/controllers/auth.controller.js
  src/controllers/flight.controller.js
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/middlewares/__test__/auth.test.js
  src/middlewares/__test__/errorHandler.test.js
  src/middlewares/auth.js
  src/routes/api/v1/auth.route.js
  src/routes/api/v1/flight.route.js
  src/services/__test__/auth.service.test.js
  src/services/auth.service.js
  src/services/flight.service.js
  src/utils/customError.js
  src/validations/auth.validation.js
Labels: documentation, enhancement

#22 Feat/payment v2
  package.json
  src/configs/midtransClient.js
  src/controllers/__test__/payment,controller.test.js
  src/controllers/payment.controller.js
  src/index.js
  src/routes/api/v1/index.js
  src/routes/api/v1/payment.route.js
  src/services/__test__/payment.service.test.js
  src/services/payment.service.js
  src/validations/payment.validation.js
Labels: enhancement

#25 Feat/payment v2
  prisma/schema.prisma
  src/controllers/__test__/payment,controller.test.js
  src/controllers/payment.controller.js
  src/index.js
  src/services/__test__/payment.service.test.js
  src/services/payment.service.js
  src/validations/payment.validation.js
Labels: bug, refactor

#26 Feat Flight Update #3
  .gitignore
  package.json
  prisma/schema.prisma
  prisma/seeder/flight.seed.js
  prisma/seeder/main.seed.js
  src/services/flight.service.js
Labels: enhancement

#29 Feat Flight Update
  .gitignore
  prisma/seeder/data.xlsx
  src/controllers/flight.controller.js
  src/services/__test__/flight.service.test.js
  src/services/flight.service.js
  src/utils/formatTime.js
  src/utils/graphFlight.js
  src/validations/flight.validation.js
Labels: bug, enhancement

#30 Update API #6
  .env.example
  .gitignore
  package.json
  prisma/schema.prisma
  src/configs/websocket.js
  src/controllers/booking.controller.js
  src/controllers/flight.controller.js
  src/controllers/profile.controller.js
  src/controllers/voucher.controller.js
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/index.js
  src/routes/api/v1/booking.route.js
  src/routes/api/v1/index.js
  src/routes/api/v1/profile.route.js
  src/routes/api/v1/seat.route.js
  src/routes/api/v1/voucher.route.js
  src/services/__test__/flight.service.test.js
  src/services/__test__/payment.service.test.js
  src/services/booking.service.js
  src/services/flight.service.js
  src/services/payment.service.js
  src/services/voucher.service.js
  src/utils/customError.js
  src/utils/formatTime.js
  src/utils/graphFlight.js
  src/utils/hashids.js
  src/utils/qrcode.js
  src/validations/booking.validation.js
  src/validations/flight.validation.js
  src/validations/voucher.validation.js
Labels: enhancement

#31 Feat Auth/OAuth
  .env.example
  .github/workflows/deploy.yml
  .gitignore
  package.json
  src/configs/googleOauth.js
  src/controllers/auth.controller.js
  src/routes/api/v1/auth.route.js
  src/services/auth.service.js
Labels: enhancement

#32 Update API #6
  .env.example
  .github/workflows/deploy.yml
  .gitignore
  package.json
  src/configs/googleOauth.js
  src/controllers/auth.controller.js
  src/index.js
  src/routes/api/v1/auth.route.js
  src/services/auth.service.js
  src/services/booking.service.js
Labels: enhancement

#36 Fix : Voucher Route Method Getvoucherbycode
  src/routes/api/v1/voucher.route.js
Labels: bug

#39 Feat : Menambahkan Api dan Views untuk print ticket
  src/configs/app.js
  src/controllers/booking.controller.js
  src/routes/api/v1/booking.route.js
  src/services/__test__/auth.service.test.js
  src/services/auth.service.js
  src/services/booking.service.js
  src/services/payment.service.js
  src/views/error.ejs
  src/views/send.otp.js
  src/views/tickets.ejs
Labels: enhancement

#40 Update API #7
  src/configs/app.js
  src/controllers/auth.controller.js
  src/controllers/booking.controller.js
  src/routes/api/v1/booking.route.js
  src/services/__test__/auth.service.test.js
  src/services/auth.service.js
  src/services/booking.service.js
  src/services/flight.service.js
  src/services/payment.service.js
  src/utils/graphFlight.js
  src/views/error.ejs
  src/views/send.otp.js
  src/views/tickets.ejs
Labels: enhancement

#42 Update API #8
  .gitignore
  prisma/migrations/20241203122343_init/migration.sql
  prisma/migrations/20241203125445_remove_airline_to_airport_relation/migration.sql
  prisma/migrations/20241204074659_update_tabel_airport/migration.sql
  prisma/migrations/20241204080435_update_table_voucher/migration.sql
  prisma/migrations/20241205132730_update_flight_table/migration.sql
  prisma/migrations/20241205180527_change_airport_to_terminal_in_flight/migration.sql
  prisma/migrations/20241209100659_updateenumtypevoucher/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/controllers/flight.controller.js
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/middlewares/errorHandler.js
  src/services/__test__/flight.service.test.js
  src/services/__test__/payment.service.test.js
  src/services/__test__/terminal.service.test.js
  src/services/flight.service.js
  src/services/payment.service.js
  src/services/terminal.service.js
  src/utils/customError.js
  src/utils/formatTime.js
  src/utils/graphFlight.js
  src/validations/payment.validation.js
Labels: enhancement

#46 Update API #9
  src/services/flight.service.js
  src/services/voucher.service.js
  src/utils/formatTime.js
  src/validations/airline.validation.js
  src/validations/flight.validation.js
  src/validations/voucher.validation.js
Labels: enhancement

#50 Feat/notif
  package.json
  prisma/migrations/20241126102709_init/migration.sql
  prisma/migrations/20241203014942_init/migration.sql
  prisma/migrations/20241203154658_init/migration.sql
  prisma/migrations/20241205072536_init/migration.sql
  prisma/migrations/20241206081432_init/migration.sql
  prisma/migrations/20241213143524_add_is_deleted_field/migration.sql
  prisma/migrations/20241214134745_allow_null_user_id/migration.sql
  prisma/schema.prisma
  src/configs/websocket.js
  src/controllers/__test__/notification.controller.test.js
  src/controllers/notification.controller.js
  src/index.js
  src/routes/api/v1/index.js
  src/routes/api/v1/notification.route.js
  src/services/__test__/notification.service.test.js
  src/services/notification.service.js
  src/validations/notification.validator.js
Labels: enhancement

#53 Update API #10
  package.json
  prisma/migrations/20241203125445_remove_airline_to_airport_relation/migration.sql
  prisma/migrations/20241204074659_update_tabel_airport/migration.sql
  prisma/migrations/20241204080435_update_table_voucher/migration.sql
  prisma/migrations/20241205132730_update_flight_table/migration.sql
  prisma/migrations/20241205180527_change_airport_to_terminal_in_flight/migration.sql
  prisma/migrations/20241209100659_updateenumtypevoucher/migration.sql
  prisma/migrations/20241216221604_update_schema_notif/migration.sql
  prisma/schema.prisma
  src/configs/websocket.js
  src/controllers/__test__/notification.controller.test.js
  src/controllers/__test__/voucher.controller.test.js
  src/controllers/notification.controller.js
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/index.js
  src/middlewares/__test__/auth.test.js
  src/middlewares/auth.js
  src/routes/api/v1/index.js
  src/routes/api/v1/notification.route.js
  src/services/__test__/airport.service.test.js
  src/services/__test__/city.service.test.js
  src/services/__test__/notification.service.test.js
  src/services/__test__/terminal.service.test.js
  src/services/__test__/voucher.service.test.js
  src/services/airport.service.js
  src/services/city.service.js
  src/services/notification.service.js
  src/services/terminal.service.js
  src/services/voucher.service.js
  src/validations/airport.validation.js
  src/validations/notification.validator.js
Labels: bug, documentation, enhancement

#54 Update API #11
  src/controllers/__test__/profile.controller.test.js
  src/controllers/booking.controller.js
  src/controllers/profile.controller.js
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/middlewares/__test__/auth.test.js
  src/middlewares/auth.js
  src/routes/api/v1/airline.route.js
  src/routes/api/v1/airport.route.js
  src/routes/api/v1/city.route.js
  src/routes/api/v1/country.route.js
  src/routes/api/v1/flight.route.js
  src/routes/api/v1/index.js
  src/routes/api/v1/notification.route.js
  src/routes/api/v1/terminal.route.js
  src/routes/api/v1/user.route.js
  src/routes/api/v1/voucher.route.js
Labels: documentation, enhancement

#55 Update API #12
  README.md
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/routes/api/v1/city.route.js
  src/routes/api/v1/country.route.js
  src/routes/api/v1/flight.route.js
  src/routes/api/v1/index.js
Labels: documentation, enhancement

#56 feat: country, terminal | update validation
  prisma/migrations/20241216221603_init/migration.sql
  src/controllers/country.controller.js
  src/services/terminal.service.js
  src/validations/country.validation.js
  src/validations/terminal.validation.js
Labels: enhancement

#57 fix: bug and update some feat and doc
  prisma/migrations/20241217081247_update/migration.sql
  src/configs/app.js
  src/controllers/__test__/country.controller.test.js
  src/docs/API-Tiketku.postman_collection.json
  src/routes/api/v1/booking.route.js
  src/routes/api/v1/index.js
  src/services/__test__/terminal.service.test.js
Labels: bug, enhancement

#59 Update Store Booking
  src/services/booking.service.js
Labels: enhancement

#60 Update API #11
  src/controllers/auth.controller.js
  src/controllers/booking.controller.js
  src/validations/auth.validation.js
Labels: bug

#61 Feat/payment v2
  src/services/__test__/payment.service.test.js
  src/services/payment.service.js
Labels: enhancement

#62 Merge fix/bookings into develop
  src/services/booking.service.js
Labels: enhancement

#63 Update API #12
  src/controllers/__test__/auth.controller.test.js
  src/controllers/__test__/flight.controller.test.js
  src/controllers/__test__/notification.controller.test.js
  src/controllers/__test__/payment,controller.test.js
  src/controllers/__test__/profile.controller.test.js
  src/middlewares/__test__/auth.test.js
  src/middlewares/__test__/errorHandler.test.js
  src/middlewares/__test__/multer.test.js
  src/middlewares/multer.js
  src/services/__test__/payment.service.test.js
  src/services/booking.service.js
  src/services/payment.service.js
Labels: enhancement

#65 Fix Payment - bug
  prisma/migrations/20241217081247_update/migration.sql
  prisma/migrations/20241218063642_init/migration.sql
  src/services/__test__/airport.service.test.js
  src/services/__test__/auth.service.test.js
  src/services/__test__/city.service.test.js
  src/services/__test__/flight.service.test.js
  src/services/__test__/payment.service.test.js
  src/services/__test__/terminal.service.test.js
  src/services/auth.service.js
  src/services/payment.service.js
Labels: bug, enhancement

#67 feat: auth | Update OAuth, can register with OAuth
  src/controllers/auth.controller.js
  src/services/auth.service.js
Labels: enhancement

#73 fix: bug in create payment VA
  src/services/payment.service.js
Labels: bug

#76 Update feat booking
  src/controllers/booking.controller.js
  src/routes/api/v1/booking.route.js
  src/services/__test__/auth.service.test.js
  src/services/__test__/booking.service.test.js
  src/services/__test__/terminal.service.test.js
  src/services/__test__/voucher.service.test.js
  src/services/booking.service.js
Labels: enhancement

#77 feat: auth and bookking update
  src/services/__test__/auth.service.test.js
  src/services/auth.service.js
  src/services/booking.service.js
Labels: enhancement

#83 Update API #12
  prisma/migrations/20241221010759_add_field_deleted_at_in_user_table/migration.sql
  prisma/schema.prisma
  src/controllers/user.controller.js
  src/middlewares/__test__/errorHandler.test.js
  src/middlewares/errorHandler.js
  src/routes/api/v1/user.route.js
  src/services/__test__/auth.service.test.js
  src/services/__test__/user.service.test.js
  src/services/auth.service.js
  src/services/user.service.js
Labels: enhancement

#84 New Feat: Flight, destination favorites
  prisma/migrations/20241221032204_add_field_image_in_cities_table/migration.sql
  prisma/schema.prisma
  src/controllers/flight.controller.js
  src/routes/api/v1/flight.route.js
  src/services/flight.service.js
Labels: enhancement

#88 Update API #14
  prisma/migrations/20241221010759_add_field_deleted_at_in_user_table/migration.sql
  prisma/migrations/20241221032204_add_field_image_in_cities_table/migration.sql
  prisma/migrations/20241221070953_init/migration.sql
  prisma/seeder/city.seed.js
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/services/__test__/payment.service.test.js
  src/services/booking.service.js
  src/services/payment.service.js
  src/utils/generateQrcode.js
  src/utils/sendPaymentEmail.js
  src/views/send.email.payment.js
Labels: documentation
