Repository travelynk/final-project-backend, pull requests merged in 2024-11, with the labels that each got.

#2 Refactor Project
  .env.example
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  babel.config.json
  eslint.config.js
  package-lock.json
  package.json
  prisma/schema.prisma
  src/configs/app.js
  src/configs/database.js
  src/controllers/__test__/auth.controller.test.js
  src/controllers/auth.controller.js
  src/controllers/index.js
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
  src/index.js
  src/middlewares/__test__/errorHandler.test.js
  src/middlewares/errorHandler.js
  src/routes/api/v1/auth.route.js
  src/routes/api/v1/index.js
  src/services/__test__/auth.service.test.js
  src/services/auth.service.js
  src/utils/customError.js
  src/utils/db.js
  src/utils/response.js
  src/validations/auth.validation.js
Labels: refactor

#5 chore: update cd
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  package.json
  prisma/schema.prisma
  src/docs/API-Tiketku.postman_collection.json
  src/docs/api-v1.json
Labels: bug

#11 Feat/resetpw
  src/controllers/__test__/auth.controller.test.js
  src/controllers/auth.controller.js
  src/routes/api/v1/auth.route.js
  src/services/__test__/auth.service.test.js
  src/services/auth.service.js
  src/validations/auth.validation.js
Labels: enhancement

#16 Feat/login
  src/controllers/__test__/auth.controller.test.js
  src/controllers/auth.controller.js
  src/services/__test__/auth.service.test.js
  src/services/auth.service.js
  src/validations/auth.validation.js
Labels: enhancement

#17 Feat/flight
  package.json
  prisma/schema.prisma
  src/controllers/airline.controller.js
  src/controllers/airport.controller.js
  src/controllers/city.controller.js
  src/controllers/country.controller.js
  src/controllers/flight.controller.js
  src/controllers/terminal.controller.js
  src/middlewares/errorHandler.js
  src/routes/api/v1/airline.route.js
  src/routes/api/v1/airport.route.js
  src/routes/api/v1/city.route.js
  src/routes/api/v1/country.route.js
  src/routes/api/v1/flight.route.js
  src/routes/api/v1/index.js
  src/routes/api/v1/terminal.route.js
  src/services/airline.service.js
  src/services/airport.service.js
  src/services/city.service.js
  src/services/country.service.js
  src/services/flight.service.js
  src/services/terminal.service.js
  src/utils/generateSeatCode.js
  src/utils/response.js
  src/validations/airline.validation.js
  src/validations/airport.validation.js
  src/validations/city.validation.js
  src/validations/country.validation.js
  src/validations/flight.validation.js
  src/validations/terminal.validation.js
Labels: enhancement
